# Docker Compose YML Config

# frontend:
#   image: jtarball/docker-polymer:latest
#   env_file:
#     - env
#   expose:
#     - "3000"


backend:
  build: docker/django
  env_file:
    - env
  expose:
    - "8000"
  links:
    - postgres:postgres


postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql